import os
from types import SimpleNamespace
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_huggingface import HuggingFaceEmbeddings
from llm.groq_llm import get_structured_completion
from qdrant_client import QdrantClient, models

load_dotenv()



embeddings_model = HuggingFaceEmbeddings(
    model_name="BAAI/bge-large-en-v1.5",
    model_kwargs={"device": "cpu"}
)


class FinancialMetrics(BaseModel):
    revenue: str | int | None = Field(None, alias="Revenue")
    net_income: str | int | None = Field(None, alias="Net Income")
    operating_income: str | int | None = Field(None, alias="Operating Income")
    cash_flow: str | int | None = Field(None, alias="Cash Flow from Operating Activities")
    total_assets: str | int | None = Field(None, alias="Total Assets")
    total_liabilities: str | int | None = Field(None, alias="Total Liabilities")
    risk_factors: str | list | None = Field(None, alias="Top Risk Factors")
    growth_drivers: str | list | None = Field(None, alias="Top Growth Drivers")


class Retriever:
    def __init__(self, client: QdrantClient, collection_name: str = "investor_intelligence"):
        self.client = client
        self.collection_name = collection_name

    def invoke(
        self,
        query: str,
        company: str | None = None,
        year: int | None = None,
        top_k: int = 20
    ) -> list:
        """
        Retrieve relevant chunks from Qdrant Cloud using modern query_points interface.
        """
        # 1. Convert text to vector embedding
        query_vector = embeddings_model.embed_query(query)

        # 2. Qdrant filter setup (Matches payload schema generated by ingest_documents.py)
        filter_conditions = []

        if company:
            filter_conditions.append(
                models.FieldCondition(
                    key="company",  # Ingestion ke continuous payload keys se sync kiya
                    match=models.MatchValue(value=company)
                )
            )
        if year:
            filter_conditions.append(
                models.FieldCondition(
                    key="year", 
                    match=models.MatchValue(value=year)
                )
            )

        qdrant_filter = models.Filter(must=filter_conditions) if filter_conditions else None

        # 3. Modern point query wrapper to strictly avoid 'search' AttributeError
        response = self.client.query_points(
            collection_name=self.collection_name,
            query=query_vector,
            query_filter=qdrant_filter,
            limit=top_k
        )

        documents = []

        # 4. Extract content chunks safely using SimpleNamespace
        for point in response.points:
            payload = point.payload or {}
            content = payload.get("page_content") or payload.get("content") or ""
            
            documents.append(
                SimpleNamespace(
                    page_content=content
                )
            )

        return documents


def retrieve_context(
    retriever: Retriever,
    company: str,
    year: int
) -> str:
    """
    Retrieve broad financial context from the vector store.
    """
    query = f"""
    Annual report financial statements,
    income statement,
    balance sheet,
    cash flow statement,
    risks,
    growth drivers,
    financial performance
    for {company} fiscal year {year}
    """

    documents = retriever.invoke(
        query=query,
        company=company,
        year=year,
        top_k=6
    )
    return "\n\n".join(
        doc.page_content
        for doc in documents
    )


def build_extraction_prompt(
    company: str,
    year: int,
    context: str
) -> str:
    """
    Build KPI extraction prompt.
    """
    return f"""
You are an expert financial analyst.

Company: {company}
Year: {year}

Context:
{context}

Extract the following information:

1. Revenue
2. Net Income
3. Operating Income
4. Cash Flow from Operating Activities
5. Total Assets
6. Total Liabilities
7. Top Risk Factors
8. Top Growth Drivers

Instructions:

- Use only the provided context.
- Return null if unavailable.
- Financial values must match the report exactly.
- Risk factors should be concise.
- Growth drivers should be concise.
- Return valid JSON only.
"""


def extract_financial_metrics(
    retriever: Retriever,
    company: str,
    year: int
) -> dict:
    """
    Extract KPIs using RAG.
    """
    context = retrieve_context(
        retriever=retriever,
        company=company,
        year=year
    )

    prompt = build_extraction_prompt(
        company=company,
        year=year,
        context=context
    )

    metrics = get_structured_completion(
        prompt=prompt,
        response_model=FinancialMetrics
    )

    return metrics.model_dump()


def main() -> None:
    company = "Apple"
    year = 2024

    # Fetch Cloud Engine configs properly
    qdrant_url = os.getenv("QDRANT_URL") or "http://localhost:6333"
    qdrant_api_key = os.getenv("QDRANT_API_KEY")

    # Fixed: Passing api_key here for Cloud Cluster handshake
    vector_store = QdrantClient(
        url=qdrant_url, 
        api_key=qdrant_api_key, 
        check_compatibility=False
    )

    retriever = Retriever(
        client=vector_store,
        collection_name="investor_intelligence"
    )

    results = extract_financial_metrics(
        retriever=retriever,
        company=company,
        year=year
    )

    print(f"\nExtracted KPIs for {company} {year}\n")

    for key, value in results.items():
        print(f"{key}:")
        print(value)
        print("-" * 80)

    from database.save_metrics import save_metrics

    save_metrics(
        company=company,
        year=year,
        metrics=results
    )

if __name__ == "__main__":
    main()